package com.dh.mapper;

import com.dh.entity.ZodiacSign;
import com.dh.entity.ZodiacSignExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZodiacSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    long countByExample(ZodiacSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    int deleteByExample(ZodiacSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    int insert(ZodiacSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    int insertSelective(ZodiacSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    List<ZodiacSign> selectByExample(ZodiacSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    ZodiacSign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZodiacSign record, @Param("example") ZodiacSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZodiacSign record, @Param("example") ZodiacSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZodiacSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZodiacSign record);
}