package com.dh.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zodiac_sign
 */
public class ZodiacSign implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zodiac_sign.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zodiac_sign.zodiac_name
     *
     * @mbg.generated
     */
    private String zodiacName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zodiac_sign.ranking
     *
     * @mbg.generated
     */
    private Integer ranking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zodiac_sign.id
     *
     * @return the value of zodiac_sign.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zodiac_sign.id
     *
     * @param id the value for zodiac_sign.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zodiac_sign.zodiac_name
     *
     * @return the value of zodiac_sign.zodiac_name
     *
     * @mbg.generated
     */
    public String getZodiacName() {
        return zodiacName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zodiac_sign.zodiac_name
     *
     * @param zodiacName the value for zodiac_sign.zodiac_name
     *
     * @mbg.generated
     */
    public void setZodiacName(String zodiacName) {
        this.zodiacName = zodiacName == null ? null : zodiacName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zodiac_sign.ranking
     *
     * @return the value of zodiac_sign.ranking
     *
     * @mbg.generated
     */
    public Integer getRanking() {
        return ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zodiac_sign.ranking
     *
     * @param ranking the value for zodiac_sign.ranking
     *
     * @mbg.generated
     */
    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ZodiacSign other = (ZodiacSign) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getZodiacName() == null ? other.getZodiacName() == null : this.getZodiacName().equals(other.getZodiacName()))
            && (this.getRanking() == null ? other.getRanking() == null : this.getRanking().equals(other.getRanking()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getZodiacName() == null) ? 0 : getZodiacName().hashCode());
        result = prime * result + ((getRanking() == null) ? 0 : getRanking().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zodiac_sign
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", zodiacName=").append(zodiacName);
        sb.append(", ranking=").append(ranking);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}